name: test

permissions:
  contents: write
  id-token: write
  pull-requests: write
  issues: write


on:
  issue_comment:
    type:
      - created
      - edited


jobs:
  test:
    if: contains(github.event.issue.labels.*.name, 'Cicd-Repo') && (github.event.comment.body != 'approved')
    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/setup-python@2.2.2
        with:
          python-version: 3.11
      - name: test
        env: 
          BODY: "$PWD"
          # BODY: ${{ github.event.issue.body }}

        run: |
          sleep 5

      - name: Close Issue If Repo Not Added
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
              Repo Closed By Automation 
                  
